### ISSUE TITLE
#1 | Kong Control Plane won't run unless on another driver/environment

### ISSUE THREAD

**Issue by astrvon** [adhxabre/kong-kube-test#1]
# Kong Control Plane won't run unless on another driver/environment

Found after checking up `EXTERNAL-IP` from `kong-dp-kong-proxy` on `<pending>` status after 10 minutes of running on the Docker Desktop, this part is known.

```yaml
ingressController:
  enabled: true
  env:
    publish_service: kong-dp-kong-proxy # this part is affected
    kong_admin_token: kong_admin_password
```

> [!NOTE]
> I'm still seeking solutions for this problem.
